Repository storyscript/studio, pull requests merged in 2019-12, with the labels that each got.

#151 Feat/persistent tips show
  package.json
  src/store/index.ts
  src/store/modules/Tips.ts
  src/views/Studio/index.vue
  tests/unit/store/modules/Tips.spec.ts
  tests/unit/views/Studio/index.spec.ts
  yarn.lock
Labels: enhancement 🚀

#159 fix(build): revert vue test utils update
  package.json
  yarn.lock
Labels: bug 🐛

#169 fix(routing): fix issue when redirecting to /welcome
  src/views/index.vue
  tests/unit/views/index.spec.ts
Labels: bug 🐛

#163 feat(help-dropdown): add component + adapt tips/intercom/icons
  src/Studio.vue
  src/assets/styles/custom/_drop.scss
  src/components/Drop.vue
  src/components/HelpDrop.vue
  src/components/Navbar.vue
  src/components/Toolbar.vue
  src/components/icons.json
  src/plugins/intercom.ts
  src/store/modules/Tips.ts
  src/views/Studio/index.vue
  tailwind.config.js
  tests/e2e/fullscreen.e2e.ts
  tests/e2e/intercom.e2e.ts
  tests/e2e/navbar.e2e.ts
  tests/unit/Studio.spec.ts
  tests/unit/components/Drop.spec.ts
  tests/unit/components/HelpDrop.spec.ts
  tests/unit/store/modules/Tips.spec.ts
  vue.config.js
Labels: enhancement 🚀

#170 Fix/tips
  src/components/Intro.vue
  src/models/StorySample.ts
  src/samples/counter.ts
  src/views/Studio/index.vue
Labels: bug 🐛

#181 chore: update all dependencies
  jest.config.js
  package.json
  tests/e2e/architecture.e2e.ts
  tests/e2e/puppeteer.config.js
  yarn.lock
Labels: chore ⛓

#192 feat(library): add library pane
  package.json
  public/img/illustrations/library/services.png
  src/app/router.ts
  src/app/store/index.ts
  src/app/store/modules/LibraryPane.ts
  src/app/views/Layout/Navbar.vue
  src/app/views/Layout/index.vue
  src/app/views/Library/index.vue
  src/assets/styles/custom/_sizes.scss
  src/internal/components/Toolbar.vue
  tailwind.config.js
  tests/e2e/feedback.e2e.ts
  tests/e2e/toolbar.e2e.ts
  tests/unit/components/Inputs/Input.spec.ts
  tests/unit/components/Toolbar.spec.ts
  tests/unit/store/modules/LibraryPane.spec.ts
  tests/unit/views/Layout/Navbar.spec.ts
  tests/unit/views/Layout/index.spec.ts
  tests/unit/views/Library/index.spec.ts
  yarn.lock
Labels: enhancement 🚀

#193 feat(editor): add editor pane views + editor classes + tests
  .eslintrc.js
  jest.config.js
  src/app/router.ts
  src/app/service-worker.js
  src/app/views/Editor/EditorPane.vue
  src/app/views/Editor/InfosPane.vue
  src/app/views/Editor/index.vue
  src/app/views/Layout/index.vue
  src/app/views/Library/index.vue
  src/app/views/index.vue
  src/assets/styles/custom/_sizes.scss
  src/editor/core/types/editor.d.ts
  src/editor/core/types/editor.ts
  src/editor/core/views/MonacoEditor.vue
  tailwind.config.js
  tests/unit/components/MonacoEditor.spec.ts
  tests/unit/types/editor.spec.ts
  tests/unit/views/Editor/EditorPane.spec.ts
  tests/unit/views/Editor/InfosPane.spec.ts
  tests/unit/views/Editor/index.spec.ts
  tests/unit/views/Library/index.spec.ts
  tests/unit/views/index.spec.ts
  vue.config.js
Labels: enhancement 🚀
