Repository storyscript/studio, pull requests merged in 2019-11, with the labels that each got.

#31 PL-1105 - Prospective storyscripter is guided by informational indicators
  src/assets/styles/custom/_drop.scss
  src/components/Drop.vue
  src/components/Intro.vue
  src/components/Navbar.vue
  src/components/Tip.vue
  src/models/StorySample.ts
  src/samples/counter.ts
  src/views/Playground/index.vue
  tests/e2e/intercom.e2e.ts
  tests/e2e/login.e2e.ts
  tests/e2e/logs.e2e.ts
  tests/e2e/percy.e2e.ts
  tests/e2e/tip.e2e.ts
  tests/unit/components/Drop.spec.ts
  tests/unit/components/Intro.spec.ts
  tests/unit/views/Playground/index.spec.ts
Labels: enhancement 🚀

#34 [PL-1106] - Prospective storyscripter can see single example on the playground welcome page
  src/Playground.vue
  src/assets/img/redis.svg
  src/assets/styles/custom/_index.scss
  src/assets/styles/custom/_scrollbar.scss
  src/components/Intro.vue
  src/components/Navbar.vue
  src/models/StorySample.ts
  src/router.ts
  src/samples/counter.ts
  src/samples/index.ts
  src/views/Playground/Logs.vue
  src/views/Playground/index.vue
  src/views/Welcome.vue
  src/views/index.vue
  tailwind.config.js
  tests/e2e/intro.e2e.ts
  tests/e2e/percy.e2e.ts
  tests/e2e/welcome.e2e.ts
  tests/unit/samples/counter.spec.ts
  tests/unit/views/Playground/Logs.spec.ts
  tests/unit/views/Playground/index.spec.ts
  tests/unit/views/Welcome.spec.ts
  tests/unit/views/index.spec.ts
Labels: enhancement 🚀

#37 PL-1124 - Allow tips to be skipped
  src/components/Intro.vue
  src/views/Playground/Logs.vue
  src/views/Playground/index.vue
  src/views/index.vue
  tests/e2e/intro.e2e.ts
  tests/unit/components/Intro.spec.ts
  tests/unit/views/Playground/Logs.spec.ts
  tests/unit/views/Playground/index.spec.ts
  tests/unit/views/index.spec.ts
Labels: chore ⛓, enhancement 🚀

#42 feat(form): success indicator
  src/components/Inputs/Input.vue
  src/views/Login.vue
  tests/e2e/login.e2e.ts
  tests/unit/views/Login.spec.ts
Labels: enhancement 🚀

#38 [PL-1023] - Prospective storyscripter sees architecture diagram for example story
  public/img/services/http.svg
  public/img/services/kubernetes-full.png
  public/img/services/kubernetes-full.svg
  public/img/services/python.svg
  public/img/services/redis.svg
  src/assets/styles/custom/_sizes.scss
  src/components/icons.json
  src/models/StorySample.ts
  src/samples/counter.ts
  src/views/Playground/Architecture.vue
  src/views/Playground/Logs.vue
  src/views/Playground/index.vue
  src/views/Welcome.vue
  tailwind.config.js
  tests/e2e/architecture.e2e.ts
  tests/e2e/login.e2e.ts
  tests/unit/samples/counter.spec.ts
  tests/unit/views/Playground/Architecture.spec.ts
  tests/unit/views/Playground/Logs.spec.ts
Labels: enhancement 🚀

#46 feat(archi): services in diagram appear on deploy
  jest.config.js
  src/assets/styles/custom/_sizes.scss
  src/assets/styles/utilities/_transitions.scss
  src/views/Playground/Architecture.vue
  src/views/Playground/Logs.vue
  tests/e2e/architecture.e2e.ts
  tests/unit/samples/counter.spec.ts
  tests/unit/samples/index.spec.ts
  tests/unit/views/Playground/Architecture.spec.ts
Labels: enhancement 🚀

#47 fix(pwa): add notification to update pwa -- should fix pwa cache update
  .gitignore
  netlify.toml
  public/_redirects
  src/Playground.vue
  src/components/Notification.vue
  src/views/Playground/index.vue
  src/views/Welcome.vue
  src/views/index.vue
Labels: bug 🐛

#53 chore(assets): update kubernetes logo
  public/img/services/kubernetes-full.png
  public/img/services/kubernetes-full.svg
  public/img/services/kubernetes.png
  public/img/services/kubernetes@2x.png
  public/img/services/kubernetes@3x.png
  src/views/Playground/Architecture.vue
Labels: chore ⛓

#55 feat(welcome): embed tweet in counter card
  public/img/services/redis.svg
  public/img/welcome-cards/counter-tweet.png
  src/models/StorySample.ts
  src/samples/counter.ts
  src/views/Welcome.vue
  tailwind.config.js
Labels: enhancement 🚀

#56 feat(welcome): icons for services used in story should appear on card on welcome page
  src/views/Welcome.vue
Labels: enhancement 🚀

#57 feat(editor): add demo pill
  src/views/Playground/index.vue
Labels: enhancement 🚀

#63 feat(collaborators): add inkie friends collaborators in the navbar
  public/img/inkie-friends/calmarie.png
  public/img/inkie-friends/crabbie.png
  public/img/inkie-friends/inkie.png
  public/img/inkie-friends/sharkie.png
  public/img/inkie-friends/whalie.png
  src/components/Collaborators.vue
  src/components/Navbar.vue
  src/directives/index.ts
  src/models/StorySample.ts
  src/router.ts
  src/samples/counter.ts
  src/samples/defaultCollaborators.ts
  src/samples/file.ts
  src/store/modules/Payload.ts
  src/views/Playground/index.vue
  tests/e2e/welcome.e2e.ts
  tests/unit/components/Collaborators.spec.ts
  tests/unit/components/Modals/index.spec.ts
  tests/unit/store/modules/Payload.spec.ts
  tests/unit/views/Playground/index.spec.ts
  tests/unit/views/Welcome.spec.ts
Labels: enhancement 🚀

#64 feat(collaborators): collaborators have names that pop up
  public/img/inkie-friends/calmarie@2x.png
  public/img/inkie-friends/calmarie@3x.png
  public/img/inkie-friends/crabbie@2x.png
  public/img/inkie-friends/crabbie@3x.png
  public/img/inkie-friends/inkie@2x.png
  public/img/inkie-friends/inkie@3x.png
  public/img/inkie-friends/sharkie@2x.png
  public/img/inkie-friends/sharkie@3x.png
  public/img/inkie-friends/whalie@2x.png
  public/img/inkie-friends/whalie@3x.png
  src/assets/styles/custom/_transitions.scss
  src/components/Collaborators.vue
  src/components/Notification.vue
  src/models/StorySample.ts
  src/samples/defaultCollaborators.ts
  src/views/Playground/index.vue
  tests/unit/components/Collaborators.spec.ts
Labels: enhancement 🚀

#66 feat: comments & tabs
  src/assets/styles/custom/_sizes.scss
  src/components/Button.vue
  src/components/Comments.vue
  src/components/Tabs.vue
  src/models/StorySample.ts
  src/samples/counter.ts
  src/views/Playground/index.vue
  tests/e2e/login.e2e.ts
  tests/unit/components/Comments.spec.ts
  tests/unit/components/Tabs.spec.ts
Labels: enhancement 🚀

#65 Services move from staging to healthy instead of deploy logs
  src/components/Navbar.vue
  src/samples/counter.ts
  src/store/modules/Logs.ts
  src/views/Playground/Architecture.vue
  src/views/Playground/Logs.vue
  src/views/Playground/index.vue
  tests/e2e/architecture.e2e.ts
  tests/e2e/logs.e2e.ts
  tests/e2e/percy.e2e.ts
  tests/unit/components/Navbar.spec.ts
  tests/unit/samples/index.spec.ts
  tests/unit/store/modules/Logs.spec.ts
  tests/unit/views/Playground/Architecture.spec.ts
  tests/unit/views/Playground/Logs.spec.ts
Labels: enhancement 🚀

#70 feat(events): add event bubbles
  src/components/Tabs.vue
  src/models/StorySample.ts
  src/samples/counter.ts
  src/views/Playground/Events.vue
  src/views/Playground/index.vue
  tailwind.config.js
  tests/e2e/architecture.e2e.ts
  tests/e2e/events.e2e.ts
  tests/unit/views/Playground/Events.spec.ts
Labels: enhancement 🚀

#72 fix(collaborators): fix issue where the collaborators are not loaded
  src/components/Collaborators.vue
Labels: bug 🐛

#73 refactor: rebranding Playground to Studio
  .env.loval
  .github/workflows/build-docker.yml
  .github/workflows/e2e.yml
  .github/workflows/storyscript.yml
  .github/workflows/unit.yml
  .gitignore
  README.md
  docker-compose.yml
  package.json
  postcss.config.js
  public/index.html
  public/manifest.json
  src/Studio.vue
  src/components/Navbar.vue
  src/components/icons.json
  src/main.ts
  src/router.ts
  src/views/NotFound.vue
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  src/views/Studio/index.vue
  src/views/Welcome.vue
  src/views/index.vue
  tests/e2e/intercom.e2e.ts
  tests/e2e/login.e2e.ts
  tests/e2e/percy.e2e.ts
  tests/e2e/tip.e2e.ts
  tests/e2e/welcome.e2e.ts
  tests/unit/Studio.spec.ts
  tests/unit/views/Studio/Architecture.spec.ts
  tests/unit/views/Studio/Events.spec.ts
  tests/unit/views/Studio/index.spec.ts
  tests/unit/views/Welcome.spec.ts
  vue.config.js
Labels: chore ⛓

#76 Move first tip to right of demo label
  src/samples/counter.ts
Labels: enhancement 🚀

#77 chore(release): 0.1.0
  CHANGELOG.md
  package.json
Labels: chore ⛓

#74 feat(editor): add fullscreen behavior
  src/components/Tabs.vue
  src/components/icons.json
  src/views/Studio/Events.vue
  src/views/Studio/index.vue
  tests/e2e/fullscreen.e2e.ts
  tests/unit/views/Studio/index.spec.ts
Labels: enhancement 🚀

#69 Add gmail autolabel example
  public/img/services/gmail.svg
  public/img/services/http.svg
  public/img/services/machinebox.svg
  public/img/services/redis.svg
  public/img/welcome-cards/autolabel-tweet.png
  src/components/Comments.vue
  src/samples/autolabel.story
  src/samples/autolabel.ts
  src/samples/counter.ts
  src/samples/index.ts
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  src/views/Welcome.vue
  tests/e2e/architecture.e2e.ts
  tests/e2e/welcome.e2e.ts
  tests/unit/components/Comments.spec.ts
  tests/unit/views/Studio/Events.spec.ts
Labels: enhancement 🚀

#92 fix(events): fix events
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  tests/e2e/architecture.e2e.ts
Labels: bug 🐛

#94 refactor(footer): disable full footer on welcome page
  src/views/Welcome.vue
Labels: enhancement 🚀

#96 chore(release): 0.2.0
  .env.loval
  .lighthouse-badges/lighthouse.svg
  .lighthouse-badges/lighthouse_accessibility.svg
  .lighthouse-badges/lighthouse_performance.svg
  .lighthouse-badges/lighthouse_pwa.svg
  CHANGELOG.md
  functions/submission-created.js
  package.json
  public/img/services/gmail.svg
  public/img/services/http.svg
  public/img/services/machinebox.svg
  public/img/services/mailgun.svg
  public/img/services/postgres.svg
  public/img/services/redis.svg
  public/img/services/stripe.svg
  public/img/services/zoom.svg
  public/img/welcome-cards/autolabel-tweet.png
  public/img/welcome-cards/stripe-tweet.png
  public/img/welcome-cards/zoom-tweet.png
  src/components/Comments.vue
  src/components/Navbar.vue
  src/components/Tabs.vue
  src/components/icons.json
  src/models/StorySample.ts
  src/samples/autolabel.story
  src/samples/autolabel.ts
  src/samples/counter.ts
  src/samples/file.ts
  src/samples/index.ts
  src/samples/stripe.story
  src/samples/stripe.ts
  src/samples/zoom.story
  src/samples/zoom.ts
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  src/views/Studio/index.vue
  src/views/Welcome.vue
  tests/e2e/architecture.e2e.ts
  tests/e2e/events.e2e.ts
  tests/e2e/fullscreen.e2e.ts
  tests/e2e/navbar.e2e.ts
  tests/e2e/welcome.e2e.ts
  tests/unit/components/Comments.spec.ts
  tests/unit/views/Studio/Events.spec.ts
  tests/unit/views/Studio/index.spec.ts
  yarn.lock
Labels: chore ⛓

#100 fix(publish): fix publish issue
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  tests/unit/views/Studio/Architecture.spec.ts
Labels: bug 🐛

#102 chore(release): 0.3.0
  CHANGELOG.md
  jest.config.js
  package.json
  src/samples/autolabel.ts
  src/samples/counter.ts
  src/samples/stripe.ts
  src/samples/zoom.ts
  src/views/Login.vue
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  tests/e2e/login.e2e.ts
  tests/unit/views/Studio/Architecture.spec.ts
Labels: chore ⛓

#107 chore(release): 0.3.1 - GHU changes
  CHANGELOG.md
  README.md
  package.json
  src/samples/autolabel.story
  src/samples/counter.ts
Labels: chore ⛓

#117 chore: update multiple dependencies
  .eslintrc.js
  package.json
  src/Studio.vue
  src/components/Blur.vue
  src/components/Button.vue
  src/components/Collaborators.vue
  src/components/Comments.vue
  src/components/Drop.vue
  src/components/Inputs/Input.vue
  src/components/Inputs/LabeledInput.vue
  src/components/Intro.vue
  src/components/Navbar.vue
  src/components/Notification.vue
  src/components/PerfectScrollbar.vue
  src/components/Tabs.vue
  src/directives/index.ts
  src/models/Display.ts
  src/models/StorySample.ts
  src/plugins/intercom.ts
  src/plugins/storyscript.lang.js
  src/samples/autolabel.ts
  src/samples/counter.ts
  src/samples/file.ts
  src/samples/index.ts
  src/samples/stripe.ts
  src/samples/zoom.ts
  src/types/intercom.d.ts
  src/types/monaco.d.ts
  src/types/shims-tsx.d.ts
  src/views/Login.vue
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  src/views/Studio/index.vue
  src/views/Welcome.vue
  src/views/index.vue
  tailwind.config.js
  tests/e2e/architecture.e2e.ts
  tests/e2e/events.e2e.ts
  tests/e2e/fullscreen.e2e.ts
  tests/e2e/intro.e2e.ts
  tests/e2e/navbar.e2e.ts
  tests/e2e/welcome.e2e.ts
  tests/unit/components/Blur.spec.ts
  tests/unit/components/Collaborators.spec.ts
  tests/unit/components/Comments.spec.ts
  tests/unit/components/Navbar.spec.ts
  tests/unit/components/Tabs.spec.ts
  tests/unit/components/Tip.spec.ts
  tests/unit/directives/index.spec.ts
  tests/unit/samples/index.spec.ts
  tests/unit/views/Studio/Events.spec.ts
  tests/unit/views/Studio/index.spec.ts
  tests/unit/views/Welcome.spec.ts
  tests/unit/views/index.spec.ts
  yarn.lock
Labels: chore ⛓

#119 fix(navbar): fix navbar routing issue
  package.json
  src/components/Navbar.vue
  src/views/index.vue
  tests/unit/components/Navbar.spec.ts
  tests/unit/views/index.spec.ts
Labels: bug 🐛

#120 feat(events): remove event bubble before diagram goes healthy
  src/views/Studio/Events.vue
  tests/unit/views/Studio/Events.spec.ts
Labels: enhancement 🚀

#124 feat: add deepspeech icon and update the zoom example
  public/img/services/deepspeech.svg
  src/samples/zoom.ts
Labels: enhancement 🚀

#129 chore(release): release v0.4.0
  .eslintrc.js
  .lighthouse-badges/lighthouse.svg
  CHANGELOG.md
  package.json
  public/img/services/deepspeech.svg
  src/Studio.vue
  src/components/Blur.vue
  src/components/Button.vue
  src/components/Collaborators.vue
  src/components/Comments.vue
  src/components/Drop.vue
  src/components/Inputs/Input.vue
  src/components/Inputs/LabeledInput.vue
  src/components/Intro.vue
  src/components/Navbar.vue
  src/components/Notification.vue
  src/components/PerfectScrollbar.vue
  src/components/Tabs.vue
  src/directives/index.ts
  src/models/Display.ts
  src/models/StorySample.ts
  src/plugins/intercom.ts
  src/plugins/storyscript.lang.js
  src/samples/autolabel.ts
  src/samples/counter.ts
  src/samples/file.ts
  src/samples/index.ts
  src/samples/stripe.ts
  src/samples/zoom.ts
  src/types/intercom.d.ts
  src/types/monaco.d.ts
  src/types/shims-tsx.d.ts
  src/views/Login.vue
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  src/views/Studio/index.vue
  src/views/Welcome.vue
  src/views/index.vue
  tailwind.config.js
  tests/e2e/architecture.e2e.ts
  tests/e2e/events.e2e.ts
  tests/e2e/fullscreen.e2e.ts
  tests/e2e/intro.e2e.ts
  tests/e2e/navbar.e2e.ts
  tests/e2e/welcome.e2e.ts
  tests/unit/components/Blur.spec.ts
  tests/unit/components/Collaborators.spec.ts
  tests/unit/components/Comments.spec.ts
  tests/unit/components/Navbar.spec.ts
  tests/unit/components/Tabs.spec.ts
  tests/unit/components/Tip.spec.ts
  tests/unit/directives/index.spec.ts
  tests/unit/samples/index.spec.ts
  tests/unit/views/Studio/Events.spec.ts
  tests/unit/views/Studio/index.spec.ts
  tests/unit/views/Welcome.spec.ts
  tests/unit/views/index.spec.ts
  yarn.lock
Labels: chore ⛓

#130 feat(archi): remove k8s and story tiles + col displaying
  .github/CODEOWNERS
  src/views/Studio/Architecture.vue
Labels: enhancement 🚀

#132 style(archi): rename Architecture to Services
  src/views/Studio/Architecture.vue
Labels: enhancement 🚀

#133 style(archi): new grid layout
  src/assets/styles/custom/_sizes.scss
  src/views/Studio/Architecture.vue
Labels: enhancement 🚀

#134 feat(share): add share btn + copy to clipboard
  package.json
  src/components/Button.vue
  src/components/Icon.vue
  src/components/Navbar.vue
  src/components/icons.json
  src/plugins/clipboard.ts
  src/plugins/index.ts
  src/views/Share.vue
  tests/e2e/share.e2e.ts
  tests/unit/views/Share.spec.ts
  yarn.lock
Labels: enhancement 🚀

#141 Feat/story titles
  src/models/StorySample.ts
  src/samples/autolabel.ts
  src/samples/counter.ts
  src/samples/file.ts
  src/samples/stripe.ts
  src/samples/zoom.ts
  src/views/Studio/Architecture.vue
  src/views/Studio/Events.vue
  src/views/Studio/index.vue
  src/views/Welcome.vue
  tests/e2e/welcome.e2e.ts
  tests/unit/samples/index.spec.ts
  tests/unit/views/Studio/Architecture.spec.ts
  tests/unit/views/Studio/Events.spec.ts
Labels: enhancement 🚀

#143 feat(remove-labels): remove studio view labels
  src/views/Studio/index.vue
Labels: enhancement 🚀

#150 feat:(navbar): implement new design
  src/assets/styles/custom/_backgrounds.scss
  src/assets/styles/mixins/_gradients.scss
  src/assets/styles/mixins/_index.scss
  src/assets/styles/tailwind.scss
  src/assets/styles/utilities/_animations.scss
  src/components/Navbar.vue
  src/components/icons.json
  src/views/Share.vue
  src/views/Studio/index.vue
  src/views/Welcome.vue
  src/views/index.vue
  tailwind.config.js
  tests/e2e/login.e2e.ts
  tests/e2e/navbar.e2e.ts
  tests/e2e/percy.e2e.ts
  tests/e2e/tip.e2e.ts
  tests/e2e/welcome.e2e.ts
  tests/unit/views/index.spec.ts
  vue.config.js
Labels: enhancement 🚀
